# Generated by Django 5.1.4 on 2024-12-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr', '0002_alter_boards_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='boards',
            name='project_description',
            field=models.TextField(max_length=100),
        ),
    ]
